# Basic
title: 秦缘在渝
subtitle: 个人博客
description: 欢迎来到我的个人博客~
# 头像里面的标题
avatarTitle: bg8iai
# 头像里面的描述
avatarDesc: linux / 业余无线电
url: "https://qindaijun.github.io"

# 博客是否自动生成目录，false为不生成
enableToc: true

# Comment
comment:
    # livere: MTAyMC81MDk5NC8yNzQ3Ng  # https://www.livere.com
    disqus: qindaijun
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    #weibo: 000000 
    github: qindaijun
    # zhihu: qindaijun
    # juejin: xxx
    jianshu: 39d62e951680
    # 汤不热: 
    mail: qindaijun@139.com


# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: XXoo  

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id: xxoo 
    host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/leopardpan/leopardpan.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}          
    - {title: 关于我, description: about, url: '/about'}   
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"



theme: jekyll-theme-cayman
